POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "firstName": "aaaa",
    "lastName": "Aaa",
    "email": "aaa@aa.fr",
    "password": "aaa" 
}
###
GET http://localhost:3000/api/auth/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJpYXQiOjE2MjM2ODU1MTIsImV4cCI6MTYyMzc3MTkxMn0.mZHSvVv13Ehbkk83rd2UQ8QbuKrK_YKT1ght8ikbKjE
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "aaa@aa.fr",
    "password": "aaa"
    }
###
GET http://localhost:3000/api/auth/17
###
POST http://localhost:3000/api/article/postarticle
Content-Type: application/json

{
    "title": "Nouvel article",
    "description": "un article test",
    "textArticle": "Lorem ipsum dolor sit amet. In minima dolores nam dignissimos nisi qui galisum nulla ut temporibus velit aut vero deserunt aut galisum laudantium. Sed quam tempore et quod totam est consectetur nulla! Id consequuntur rerum non dolorum corrupti aut itaque illum cum aliquid ducimus sed necessitatibus dolor.",
    "userId": 5  
}
###
GET http://localhost:3000/api/article
###
